# Generated by Django 5.2.8 on 2025-11-11 14:26

import comments.utils
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_content_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=comments.utils.images_upload_path)),
                ('file', models.FileField(blank=True, null=True, upload_to=comments.utils.files_upload_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=comments.utils.videos_upload_path)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(help_text='The actual text of the comment', max_length=3000)),
                ('content_delta', models.JSONField(blank=True, help_text="The comment's text as Quill delta content", null=True)),
                ('content_html', models.TextField(blank=True, help_text='The HTML representation of the text to be displayed on the page', max_length=6000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('pinned', models.BooleanField(default=False)),
                ('original_post', models.BooleanField(default=False)),
                ('publish_on', models.DateField(blank=True, help_text='Publish the comment on a given specific date', null=True)),
                ('published', models.BooleanField(default=True, help_text='Indicates that a comment was published')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('subthread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='threads.subthread')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.mainthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('media_contents', models.ManyToManyField(blank=True, to='comments.mediacontent')),
            ],
            options={
                'ordering': ['created_on', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='The actual text of the quoted comment', max_length=3000, null=True)),
                ('content_html', models.TextField(blank=True, help_text='The HTML representation of the quoted comment to be displayed on the page', max_length=6000, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, help_text='The comment asking for the quote', null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                ('quoted_comment', models.ForeignKey(blank=True, help_text='The comment that is being quoted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoted_omment', to='comments.comment')),
            ],
        ),
        migrations.CreateModel(
            name='SavedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('created_on__gte', django.db.models.expressions.CombinedExpression(models.F('created_on'), '-', models.Value(15)))), fields=['created_on'], name='last_fifteen_days_comments'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('created_on__gte', django.db.models.expressions.CombinedExpression(models.F('created_on'), '-', models.Value(7)))), fields=['created_on'], name='last_seven_days_comments'),
        ),
    ]
