# Generated by Django 4.0.1 on 2022-06-06 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('50f3a59b-6783-4961-97f9-bda156225a79')),
        ),
    ]
