# Generated by Django 4.0.1 on 2022-06-06 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_mediacontent_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('e9830bae-f24e-4f25-850e-2dd94b06b720')),
        ),
    ]
