# Generated by Django 4.0.1 on 2022-06-06 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_mediacontent_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('2be7f738-0a69-4ebe-8695-b885749a7fff')),
        ),
    ]
