# Generated by Django 4.1.3 on 2024-01-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_mediacontent_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediacontent',
            name='reference',
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='media_content_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
