# Generated by Django 4.1.3 on 2024-01-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_remove_mediacontent_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_delta',
            field=models.JSONField(blank=True, help_text="The comment's text as Quill delta content", null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='The actual text of the comment', max_length=3000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_html',
            field=models.TextField(blank=True, help_text='The HTML representation of the text to be displayed on the page', max_length=6000, null=True),
        ),
    ]
