# Generated by Django 4.1.3 on 2024-01-10 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_content_delta_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='content',
            field=models.TextField(blank=True, help_text='The actual text of the quoted comment', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='content_html',
            field=models.TextField(blank=True, help_text='The HTML representation of the quoted comment to be displayed on the page', max_length=6000, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quoted_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoted_omment', to='comments.comment'),
        ),
    ]
