# Generated by Django 5.0.4 on 2024-05-26 21:19

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_quote_content_quote_content_html_quote_created_on_and_more'),
        ('tags', '0002_alter_tag_options'),
        ('threads', '0010_alter_mainthread_category_alter_subthread_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_title_f8d44b_idx',
        ),
        migrations.AlterField(
            model_name='quote',
            name='comment',
            field=models.ForeignKey(blank=True, help_text='The comment asking for the quote', null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoted_comment',
            field=models.ForeignKey(blank=True, help_text='The comment that is being quoted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoted_omment', to='comments.comment'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('created_on__gte', models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('created_on'), '-', models.Value(15)), output_field=models.DateTimeField()))), fields=['created_on'], name='last_fifteen_days_comments'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('created_on__gte', models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('created_on'), '-', models.Value(7)), output_field=models.DateTimeField()))), fields=['created_on'], name='last_seven_days_comments'),
        ),
    ]
