# Generated by Django 5.0.4 on 2024-05-26 21:22

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_remove_comment_last_fifteen_days_comments_and_more'),
        ('tags', '0002_alter_tag_options'),
        ('threads', '0012_alter_mainthread_category_alter_subthread_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='last_seven_days_comments',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('created_on__gte', django.db.models.expressions.CombinedExpression(models.F('created_on'), '-', models.Value(7)))), fields=['created_on'], name='last_seven_days_comments'),
        ),
    ]
