# Generated by Django 5.0.6 on 2024-12-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_remove_comment_last_seven_days_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish_on',
            field=models.DateField(blank=True, help_text='Publish the comment on a given specific date', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=True, help_text='Indicates that a comment was published'),
        ),
    ]
