# Generated by Django 5.2.8 on 2025-11-11 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('poll_type', models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple'), ('Limited', 'Limited')], default='Single', max_length=100)),
                ('choices_limit', models.PositiveIntegerField(default=2)),
                ('allow_vote_change', models.BooleanField(default=True)),
                ('closes', models.BooleanField(default=True)),
                ('closing_date', models.DateField(default=django.utils.timezone.now)),
                ('public', models.BooleanField(default=True, help_text='Determines whether the votes are visible by all')),
                ('voters_alone', models.BooleanField(default=True, help_text='Determines whether the results are visible by voters alone')),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.mainthread')),
            ],
            options={
                'verbose_name': 'poll',
            },
        ),
        migrations.CreateModel(
            name='Possibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
            options={
                'verbose_name': 'possibility',
                'verbose_name_plural': 'possibilities',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
                ('possibilities', models.ManyToManyField(to='polls.possibility')),
            ],
            options={
                'verbose_name': 'answer',
            },
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['question'], name='polls_poll_questio_d4df9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.UniqueConstraint(fields=('thread',), name='one_poll_per_thread'),
        ),
    ]
