# Generated by Django 5.2.8 on 2025-11-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple'), ('Limited', 'Limited')], default='Single', max_length=100),
        ),
    ]
