# Generated by Django 4.1.3 on 2024-01-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_poll_poll_type_poll_one_poll_per_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple'), ('Limited', 'Limited')], default='Single', max_length=100),
        ),
    ]
