# Generated by Django 5.2.8 on 2025-11-11 14:26

import tags.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[tags.validators.tag_name_validator])),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='tags_tag_name_3fbe74_idx')],
            },
        ),
    ]
