# Generated by Django 4.0.1 on 2022-06-04 10:06

from django.db import migrations, models
import tags.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[tags.validators.tag_name_validator])),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='tags_tag_name_3fbe74_idx'),
        ),
    ]
