# Generated by Django 4.0.1 on 2022-06-04 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forums.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[forums.validators.validate_title])),
                ('category', models.CharField(choices=[('General', 'General'), ('News', 'News'), ('Miscellaneous', 'Miscellaneous')], default='General', help_text='Used to regroup forums of a same category together', max_length=50)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('admin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['title'], name='forums_foru_title_b2a2ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='forum',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_forum_name'),
        ),
    ]
