# Generated by Django 5.2.8 on 2025-11-11 14:26

import django.db.models.deletion
import forums.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[forums.validators.validate_title])),
                ('category', models.CharField(choices=[('General', 'General'), ('News', 'News'), ('Miscellaneous', 'Miscellaneous')], default='General', help_text='Used to regroup forums of a same category together', max_length=50)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('admin', models.BooleanField(default=False, help_text='Specifies whether the forum is for admin purposes')),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
                'indexes': [models.Index(condition=models.Q(('active', True)), fields=['active'], name='active_forums')],
                'constraints': [models.UniqueConstraint(fields=('title',), name='unique_forum_name')],
            },
        ),
    ]
