# Generated by Django 5.0.4 on 2024-05-26 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_alter_forum_admin_alter_forum_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='forum',
            name='forums_foru_title_b2a2ed_idx',
        ),
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('News', 'News'), ('Miscellaneous', 'Miscellaneous')], default='General', help_text='Used to regroup forums of a same category together', max_length=50),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(condition=models.Q(('active', True)), fields=['active'], name='active_forums'),
        ),
    ]
