# Generated by Django 5.0.4 on 2024-05-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_remove_forum_forums_foru_title_b2a2ed_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('News', 'News'), ('Miscellaneous', 'Miscellaneous')], default='General', help_text='Used to regroup forums of a same category together', max_length=50),
        ),
    ]
