# Generated by Django 4.0.1 on 2022-06-06 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('3227c9dd-2eda-42db-a7ce-1da08bb8f447')),
        ),
    ]
