# Generated by Django 4.0.1 on 2022-06-06 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_alter_report_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('31e2b0b2-f788-4d8e-b6c6-f36147a443d3')),
        ),
    ]
