# Generated by Django 5.2.8 on 2025-11-11 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('forums', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forum_subscriptions',
            field=models.ManyToManyField(blank=True, to='forums.forum'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thread_subscriptions',
            field=models.ManyToManyField(blank=True, to='threads.mainthread'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
