# Generated by Django 4.1.3 on 2024-01-08 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_permanentban_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permanentban',
            name='category',
            field=models.CharField(choices=[('Level 1', 'Level1'), ('Level 2', 'Level2'), ('Level 3', 'Level3')], default='Level 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='permanentban',
            name='reason',
            field=models.CharField(choices=[('Racism', 'Racism'), ('Sexism', 'Sexism'), ('Bullying', 'Bullying')], default='Racism', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporaryban',
            name='category',
            field=models.CharField(choices=[('Level 1', 'Level1'), ('Level 2', 'Level2'), ('Level 3', 'Level3')], default='Level 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporaryban',
            name='reason',
            field=models.CharField(choices=[('Racism', 'Racism'), ('Sexism', 'Sexism'), ('Bullying', 'Bullying')], default='Racism', max_length=100),
        ),
    ]
