# Generated by Django 5.0.6 on 2024-12-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_permanentban_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentban',
            name='appeal_reason',
            field=models.TextField(default='Some reason', help_text='Reason invoked by the user to lift the ban'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permanentban',
            name='apply_ban_on',
            field=models.DateTimeField(blank=True, help_text='Ban a user on a specific date', null=True),
        ),
        migrations.AddField(
            model_name='temporaryban',
            name='appeal_reason',
            field=models.TextField(default='Some reason', help_text='Reason invoked by the user to lift the ban'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporaryban',
            name='apply_ban_on',
            field=models.DateTimeField(blank=True, help_text='Ban a user on a specific date', null=True),
        ),
        migrations.AlterField(
            model_name='permanentban',
            name='category',
            field=models.CharField(choices=[('Level 1', 'Level1'), ('Level 2', 'Level2'), ('Level 3', 'Level3')], default='Level 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='permanentban',
            name='reason',
            field=models.CharField(choices=[('Racism', 'Racism'), ('Sexism', 'Sexism'), ('Bullying', 'Bullying')], default='Racism', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporaryban',
            name='category',
            field=models.CharField(choices=[('Level 1', 'Level1'), ('Level 2', 'Level2'), ('Level 3', 'Level3')], default='Level 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporaryban',
            name='reason',
            field=models.CharField(choices=[('Racism', 'Racism'), ('Sexism', 'Sexism'), ('Bullying', 'Bullying')], default='Racism', max_length=100),
        ),
    ]
