# Generated by Django 5.2.8 on 2025-11-11 14:26

import django.db.models.deletion
import threads.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[threads.validators.validate_title])),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(choices=[('General discussion', 'General Discussion'), ('Bombshell', 'Bombshell'), ('Result', 'Result'), ('WWW', 'Www'), ('Draw', 'Draw'), ('Poll', 'Poll')], default='General discussion', max_length=50)),
                ('publish_on', models.DateField(blank=True, help_text='Publish the comment on a given specific date', null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True, help_text='Indicates that a thread was published')),
                ('active', models.BooleanField(default=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='main_thread_followers', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forums.forum')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[threads.validators.validate_title])),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(choices=[('General discussion', 'General Discussion'), ('Bombshell', 'Bombshell'), ('Result', 'Result'), ('WWW', 'Www'), ('Draw', 'Draw'), ('Poll', 'Poll')], default='General discussion', max_length=50)),
                ('publish_on', models.DateField(blank=True, help_text='Publish the comment on a given specific date', null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True, help_text='Indicates that a thread was published')),
                ('active', models.BooleanField(default=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forums.forum')),
                ('main_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.mainthread')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_on'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='mainthread',
            index=models.Index(fields=['title'], name='threads_mai_title_59678a_idx'),
        ),
        migrations.AddIndex(
            model_name='subthread',
            index=models.Index(fields=['title'], name='threads_sub_title_6d7162_idx'),
        ),
    ]
