# Generated by Django 4.0.1 on 2022-06-04 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import threads.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[threads.validators.validate_title])),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(choices=[('General', 'General')], default='General', max_length=50)),
                ('pinned', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forums.forum')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[threads.validators.validate_title])),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(choices=[('General', 'General')], default='General', max_length=50)),
                ('pinned', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forums.forum')),
                ('main_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.mainthread')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='subthread',
            index=models.Index(fields=['title'], name='threads_sub_title_6d7162_idx'),
        ),
        migrations.AddIndex(
            model_name='mainthread',
            index=models.Index(fields=['title'], name='threads_mai_title_59678a_idx'),
        ),
    ]
