# Generated by Django 4.0.1 on 2022-06-06 12:24

from django.db import migrations, models
import threads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainthread',
            name='category',
            field=models.CharField(choices=[('General', 'General')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='mainthread',
            name='title',
            field=models.CharField(max_length=100, validators=[threads.validators.validate_title]),
        ),
        migrations.AlterField(
            model_name='subthread',
            name='category',
            field=models.CharField(choices=[('General', 'General')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='subthread',
            name='title',
            field=models.CharField(max_length=100, validators=[threads.validators.validate_title]),
        ),
    ]
