# Generated by Django 4.1.3 on 2024-01-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_alter_mainthread_category_alter_subthread_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainthread',
            options={'ordering': ['-modified_on']},
        ),
        migrations.AlterModelOptions(
            name='subthread',
            options={'ordering': ['-modified_on']},
        ),
        migrations.AlterField(
            model_name='mainthread',
            name='category',
            field=models.CharField(choices=[('General', 'General')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='subthread',
            name='category',
            field=models.CharField(choices=[('General', 'General')], default='General', max_length=50),
        ),
    ]
