# Generated by Django 4.1.3 on 2024-01-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_alter_mainthread_options_alter_subthread_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainthread',
            name='category',
            field=models.CharField(choices=[('General', 'General')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='subthread',
            name='category',
            field=models.CharField(choices=[('General', 'General')], default='General', max_length=50),
        ),
    ]
