# Generated by Django 5.0.6 on 2024-12-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0012_alter_mainthread_category_alter_subthread_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainthread',
            name='publish_on',
            field=models.DateField(blank=True, help_text='Publish the comment on a given specific date', null=True),
        ),
        migrations.AddField(
            model_name='mainthread',
            name='published',
            field=models.BooleanField(default=True, help_text='Indicates that a thread was published'),
        ),
        migrations.AddField(
            model_name='subthread',
            name='publish_on',
            field=models.DateField(blank=True, help_text='Publish the comment on a given specific date', null=True),
        ),
        migrations.AddField(
            model_name='subthread',
            name='published',
            field=models.BooleanField(default=True, help_text='Indicates that a thread was published'),
        ),
        migrations.AlterField(
            model_name='mainthread',
            name='category',
            field=models.CharField(choices=[('General discussion', 'General Discussion'), ('Bombshell', 'Bombshell'), ('Result', 'Result'), ('WWW', 'Www'), ('Draw', 'Draw'), ('Poll', 'Poll')], default='General discussion', max_length=50),
        ),
        migrations.AlterField(
            model_name='subthread',
            name='category',
            field=models.CharField(choices=[('General discussion', 'General Discussion'), ('Bombshell', 'Bombshell'), ('Result', 'Result'), ('WWW', 'Www'), ('Draw', 'Draw'), ('Poll', 'Poll')], default='General discussion', max_length=50),
        ),
    ]
